<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro"
       name="arm_lwa4d" >
    <xacro:macro name="arm_lwa4d" params="parent:=base_link">
        <joint name="arm_podest_joint" type="fixed">
            <origin xyz="0.19 0 0.36" rpy="0 0 0" />
            <parent link="${parent}"/>
            <child link="arm_podest_link"/>
        </joint>

        <link name="arm_podest_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>

            <visual>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_podest_link.stl"/>
                </geometry>
                <material name="LightGrey"/>
            </visual>

            <collision>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_podest_link.stl"/>
                </geometry>
            </collision>
        </link>

        <joint name="arm_base_joint" type="fixed">
            <origin xyz="0 0 0.140" rpy="0 0 0" />
            <axis xyz="0 0 1"/>
            <parent link="arm_podest_link"/>
            <child link="arm_base_link"/>
        </joint>

        <link name="arm_base_link">
            <!--xacro:default_inertial/-->
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
        </link>

    <!-- joint between arm_base_link and arm_1_link -->
        <joint name="arm_1_joint" type="revolute">
            <origin xyz="0 0 0" rpy="0 0 0" />
            <axis xyz="0 0 1"/>
            <parent link="arm_base_link"/>
            <child link="arm_1_link"/>
            <limit effort="216" velocity="0.43633" lower="${-M_PI+safety_offset}" upper="${M_PI-safety_offset}"/>
        </joint>
    <!-- arm_1_link-->
        <link name="arm_1_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
            <!--
            <xacro:cylinder_inertial radius="0.06" length="0.150" mass="3.6">
                <origin xyz="0 0 0.02" rpy="0 0 0"/>
            </xacro:cylinder_inertial>
            -->
            <visual>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_1_link.stl"/>
                </geometry>
                <material name="LightGrey"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_1_link.stl"/>
                </geometry>
            </collision>
        </link>

    <!-- joint between arm_1_link and arm_2_link -->
        <joint name="arm_2_joint" type="revolute">
            <origin xyz="0 0 0.24" rpy="-${M_PI/2} -${M_PI/2} 0"/>
            <axis xyz="0 0 1"/>
            <parent link="arm_1_link"/>
            <child link="arm_2_link"/>
            <limit effort="216" velocity="0.43633" lower="${-2.14 + safety_offset}" upper="${2.14 - safety_offset}"/>
        </joint>
    <!-- arm_2_link -->
        <link name="arm_2_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
            <!--
            <xacro:cylinder_inertial radius="0.06" length="0.150" mass="2.0">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertial>
            -->
            <visual>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_2_link.stl"/>
                </geometry>
                <material name="Black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_2_link_collision.stl"/>
                </geometry>
            </collision>
        </link>

    <!-- joint between arm_2_link and arm_3_link -->
        <joint name="arm_3_joint" type="revolute">
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <parent link="arm_2_link"/>
            <child link="arm_3_link"/>
            <limit effort="81.5" velocity="0.4189" lower="${-M_PI + safety_offset}" upper="${M_PI - safety_offset}"/>
        </joint>
    <!-- arm_3_link -->
        <link name="arm_3_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
            <!--
            <xacro:cylinder_inertial radius="0.06" length="0.2" mass="2.0">
                <origin xyz="0.0 0 -0.2" rpy="0 0 0"/>
            </xacro:cylinder_inertial>
            -->
            <visual>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_3_link.stl"/>
                </geometry>
                <material name="LightGrey"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_3_link_collision.stl"/>
                </geometry>
            </collision>
        </link>

    <!-- joint between arm_3_link and arm_4_link -->
        <joint name="arm_4_joint" type="revolute">
            <origin xyz="0 0 0.328" rpy="-${M_PI/2} -${M_PI/2} 0"/>
            <axis xyz="0 0 1"/>
            <parent link="arm_3_link"/>
            <child link="arm_4_link"/>
            <limit effort="81.5" velocity="0.4189" lower="${-2.18 + safety_offset}" upper="${2.18 - safety_offset}"/>
        </joint>
    <!--arm_4_link -->
        <link name="arm_4_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
            <!--
            <xacro:cylinder_inertial radius="0.06" length="0.150" mass="1.2">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:cylinder_inertial>
            -->

            <visual>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_4_link.stl"/>
                </geometry>
            <material name="Black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_4_link_collision.stl"/>
                </geometry>
            </collision>
        </link>

    <!-- joint between arm_4_link and arm_5_link -->
        <joint name="arm_5_joint" type="revolute">
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <parent link="arm_4_link"/>
            <child link="arm_5_link"/>
            <limit effort="20.7" velocity="0.43633" lower="${-M_PI + safety_offset}" upper="${M_PI - safety_offset}"/>
        </joint>
    <!-- arm_5_link -->
        <link name="arm_5_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
            <!--
            <xacro:cylinder_inertial radius="0.06" length="0.15" mass="1.2">
                <origin xyz="0 0 -0.18" rpy="0 0 0"/>
            </xacro:cylinder_inertial>
            -->

            <visual>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_5_link.stl"/>
                </geometry>
                <material name="LightGrey"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_5_link_collision.stl"/>
                </geometry>
            </collision>
        </link>

    <!-- joint between arm_5_link and arm_6_link -->
        <joint name="arm_6_joint" type="revolute">
            <origin xyz="0 0 0.323" rpy="-${M_PI/2} -${M_PI/2} 0"/>
            <axis xyz="0 0 1"/>
            <parent link="arm_5_link"/>
            <child link="arm_6_link"/>
            <limit effort="15" velocity="1.2566" lower="${-2.96 + safety_offset}" upper="${2.96 - safety_offset}"/>
        </joint>
    <!-- arm_6_link -->
        <link name="arm_6_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
            <!--
            <xacro:sphere_inertial radius="0.05" mass="1.9">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:sphere_inertial>
            -->

            <visual>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_6_link.stl"/>
                </geometry>
                <material name="Black"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_6_link_collision.stl"/>
                </geometry>
            </collision>
        </link>

    <!-- joint between arm_6_link and arm_7_link -->
        <joint name="arm_7_joint" type="revolute">
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
            <axis xyz="0 0 1"/>
            <parent link="arm_6_link"/>
            <child link="arm_7_link"/>
            <limit effort="15" velocity="1.2566" lower="${-2.96 + safety_offset}" upper="${2.96 - safety_offset}"/>
        </joint>
    <!--arm_7_link -->
        <link name="arm_7_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
            <!--
            <xacro:cylinder_inertial radius="0.03" length="0.035" mass="0.05">
                <origin xyz="0 0 0.06" rpy="0 0 0"/>
            </xacro:cylinder_inertial>
            -->
            <visual>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_7_link.stl"/>
                </geometry>
                <material name="LightGrey"/>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://mp500lwa4d_description/meshes/lwa4d/arm_7_link.stl"/>
                </geometry>
            </collision>
        </link>

        <joint name="arm_ee_joint" type="fixed">
            <origin xyz="0 0 0.0824" rpy="0 0 0"/>
            <parent link="arm_7_link"/>
            <child link="arm_ee_link"/>
        </joint>

        <link name="arm_ee_link">
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
            </inertial>
        </link>
    
    </xacro:macro>
</robot>